### ISSUE TITLE
No data for a specific seed/difficulty/level

### ISSUE THREAD

**Issue by ghost** [soarqin/d2mapapi_mod#1]
Using the d2mapapi_piped, the program returns no data when requesting the below information:

Seed: 1445251180
Difficulty: Hell
Level: Durance of Hate Level 1 (id = 100)

It also causes jcageman's d2mapapi to crash. I opened an issue in his repo too. I'm not sure if this is something you're able to fix, or you need to have him fix first.

https://github.com/jcageman/d2mapapi/issues/16

**Comment by soarqin** [comment]
Did some debug on it, and found the crash is from D2Common.dll while calling `AddRoomData(act, 100, 3512, 1012, nullptr);` if seed is 1445251180 and difficulty is 1 or 2.
Seems like a bug in D2Legacy itself.

**Comment by soarqin** [comment]
![Image](https://user-images.githubusercontent.com/172610/167556639-17add0b8-06fd-44e8-82df-f70638f8cb94.png)
This seed also crashed D2Legacy client (you can set seed using D2Loader)

**Comment by ghost** [comment]
I appreciate you taking a look. Looks like it's just something that we'll have to live with.
